--DELETE FROM DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS;

INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_PAIS(PAIS, REGIAO)
SELECT PAIS, REGIAO
FROM DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES A
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_PAIS X WHERE A.PAIS = X.PAIS)
    AND A.PAIS = 'BRASIL'
    AND A.PAIS IS NOT NULL
GROUP BY PAIS, REGIAO
ORDER BY A.PAIS;


INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_PAIS(PAIS, REGIAO)
SELECT PAIS, REGIAO
FROM DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES A
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_PAIS X WHERE A.PAIS = X.PAIS)
    AND A.PAIS = 'PARAGUAI'
    AND A.PAIS IS NOT NULL
GROUP BY PAIS, REGIAO
ORDER BY A.PAIS;

UPDATE DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO AS X SET 
    X.FLG_STATUS = A.FLGATIVO
FROM DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS B ON A.PAIS = B.PAIS
WHERE X.LABORATORIO = NM_CLIENTE 
    AND X.ID_PAIS = B.ID_PAIS;


INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO(LABORATORIO, ID_PAIS, FLG_STATUS)
SELECT NM_CLIENTE AS LABORATORIO, B.ID_PAIS AS ID_PAIS, A.FLGATIVO
FROM DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS B ON A.PAIS = B.PAIS
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO X WHERE X.LABORATORIO = NM_CLIENTE AND X.ID_PAIS = B.ID_PAIS);


--INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO(ID_LABORATORIO, LABORATORIO, ID_PAIS, FLG_STATUS)
--VALUES (9999, 'AUDITORIA BRASIL', 1, TRUE)


UPDATE DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS AS X SET 
    X.SETOR = DADOSREP.EQZ
    , X.SETOR_CLIENTE = DADOSREP.SETOR_CLIENTE
    , X.NOME_SETOR = REP.NOME_REP
    , X.ID_LABORATORIO = LAB.ID_LABORATORIO
    , X.SETOR_VAGO = DADOSREP.FLG_VAGO
    , X.SETOR_HISTORICO = (CASE WHEN HIST.SETOR IS NOT NULL THEN TRUE ELSE FALSE END)
FROM DB_CRM_SALES_FARMA_DEV.CURATED.FAT_GDREPRESENTANTES REP
INNER JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDNDADOSREP DADOSREP ON REP.ORIGEM = DADOSREP.ORIGEM AND REP.SETOR_REP = DADOSREP.EQZ
INNER JOIN DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES BASE ON REP.ORIGEM = BASE.NMBANCO
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO LAB ON BASE.NM_CLIENTE = LAB.LABORATORIO
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GD_N_EQUIPE_HIST HIST ON REP.ORIGEM = HIST.ORIGEM AND REP.SETOR_REP = HIST.SETOR
WHERE X.ID_LABORATORIO = LAB.ID_LABORATORIO AND X.SETOR = DADOSREP.EQZ;


INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS(SETOR, SETOR_CLIENTE, NOME_SETOR, ID_LABORATORIO, SETOR_VAGO, SETOR_HISTORICO)
SELECT DISTINCT
    DADOSREP.EQZ AS SETOR
    , DADOSREP.SETOR_CLIENTE AS SETOR_CLIENTE
    , REP.NOME_REP AS NOME_SETOR
    , LAB.ID_LABORATORIO AS ID_LABORATORIO
    , DADOSREP.FLG_VAGO SETOR_VAGO
    , CASE WHEN HIST.SETOR IS NOT NULL THEN TRUE ELSE FALSE END SETOR_HISTORICO
FROM DB_CRM_SALES_FARMA_DEV.CURATED.FAT_GDREPRESENTANTES REP
INNER JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDNDADOSREP DADOSREP ON REP.ORIGEM = DADOSREP.ORIGEM AND REP.SETOR_REP = DADOSREP.EQZ
INNER JOIN DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES BASE ON REP.ORIGEM = BASE.NMBANCO
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO LAB ON BASE.NM_CLIENTE = LAB.LABORATORIO
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GD_N_EQUIPE_HIST HIST ON REP.ORIGEM = HIST.ORIGEM AND REP.SETOR_REP = HIST.SETOR
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS X WHERE X.ID_LABORATORIO = LAB.ID_LABORATORIO AND X.SETOR = DADOSREP.EQZ);



CREATE OR REPLACE TEMPORARY TABLE TEMP_MEDICO AS
SELECT DISTINCT 
    E.PROF_ID
    , COALESCE(E.UF_CRM, '') AS UF_CRM
    , COALESCE(E.CRM, '') AS CRM
    , COALESCE(UNICA_PROF.IDENT01, E.IDENT01, '') AS IDENT01
    , COALESCE(UNICA_PROF.IDENT02, E.IDENT02, '') AS IDENT02
    , COALESCE(UNICA_PROF.IDENT03, E.IDENT03, '') AS IDENT03
    , COALESCE(UNICA_PROF.IDENT04, E.IDENT04, '') AS IDENT04
    , COALESCE(UNICA_PROF.IDENT05, E.IDENT05, '') AS IDENT05
    , E.FLG_ATIVO AS FLG_STATUS
    , C.ID_PAIS AS ID_PAIS
    , LTRIM(RTRIM(UPPER(collate(E.NOME_PROF, 'en-ci-ai')))) AS NOME_PROF
    , LTRIM(RTRIM(UPPER(collate(COALESCE(ESP1.COD_ESPEC_PROF, ESP2.COD_ESPEC_PROF, 'OUT'), 'en-ci-ai')))) AS COD_ESPEC_PROF1
    , LTRIM(RTRIM(UPPER(collate(COALESCE(ESP1.DESCRICAO, ESP2.DESCRICAO, 'OUTRAS'), 'en-ci-ai')))) AS ESPEC_PROF1
    , LTRIM(RTRIM(UPPER(ESP2.COD_ESPEC_PROF))) AS COD_ESPEC_PROF2
    , LTRIM(RTRIM(UPPER(ESP2.DESCRICAO))) AS ESPEC_PROF2
    , C.ID_LABORATORIO
    , E.MERE_REP AS SETOR
    , E.DT_INSERT AS DATA_INCLUSAO
    , CASE WHEN HIST.SETOR IS NOT NULL THEN TRUE ELSE FALSE END SETOR_HISTORICO
    , COALESCE(E.MASTER_ID, 0) MASTER_ID
    , LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.ENDERECO_COMPLETO, ''), 'en-ci-ai')))) AS ENDERECO_COMPLETO
	, LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.PREFIXO_ENDERECO, ''), 'en-ci-ai')))) AS PREFIXO_ENDERECO
	, LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.ENDERECO, ''), 'en-ci-ai')))) AS ENDERECO
	, LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.BAIRRO, ''), 'en-ci-ai')))) AS BAIRRO
	, LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.CIDADE, ''), 'en-ci-ai')))) AS CIDADE
	, LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.ESTADO, ''), 'en-ci-ai')))) AS ESTADO
	, LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.NUMERO_EXTERNO, ''), 'en-ci-ai')))) AS NUMERO_EXTERNO
	, LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.NUMERO_INTERNO, ''), 'en-ci-ai')))) AS NUMERO_INTERNO
	, LTRIM(RTRIM(UPPER(collate(COALESCE(LOCAL.CODIGO_POSTAL, ''), 'en-ci-ai')))) AS CODIGO_POSTAL
    , LTRIM(RTRIM(UPPER(collate(COALESCE(E.EMAIL, ''), 'en-ci-ai')))) AS EMAIL
    , LTRIM(RTRIM(UPPER(collate(COALESCE(E.CELULAR, ''), 'en-ci-ai')))) AS CELULAR
FROM DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO C ON A.NM_CLIENTE = C.LABORATORIO
INNER JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDMEDREP E ON A.NMBANCO = E.ORIGEM
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_ESPECIALIDADEPROF ESP1 ON E.ORIGEM = ESP1.ORIGEM AND E.COD_ESPEC = ESP1.COD_ESPEC_PROF
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_ESPECIALIDADEPROF ESP2 ON E.ORIGEM = ESP2.ORIGEM AND E.COD_ESPEC2 = ESP2.COD_ESPEC_PROF
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GD_N_EQUIPE_HIST HIST ON E.ORIGEM = HIST.ORIGEM AND E.MERE_REP = HIST.SETOR
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_BASE_UNICA_PROF UNICA_PROF ON E.ORIGEM = UNICA_PROF.ORIGEM AND E.MASTER_ID = UNICA_PROF.MASTER_ID
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDNESTAB ESTAB ON E.ORIGEM = ESTAB.ORIGEM AND E.ESTAB_ID = ESTAB.ESTAB_ID
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDNESTABLOCAL LOCAL ON ESTAB.ORIGEM = LOCAL.ORIGEM AND ESTAB.ESTAB_ID = LOCAL.ESTAB_ID AND ESTAB.VIS_LOCAL_ID = LOCAL.LOCAL_ID
WHERE E.COD_TIPO_PROF = $$M$$;

/*
CREATE OR REPLACE TEMPORARY TABLE TEMP_MEDICO_MAESTRO AS
SELECT 
    MED_CODIGO_UNICO AS MED_CODIGO_UNICO
    , MED_CODIGO AS MED_CODIGO
    , MED_CODIGO_BR AS MED_CODIGO_BR
    , LEFT(MED_CRMUF, 2) UF_CRM
    , CAST(CAST(SUBSTR(MED_CRMUF, 3, LENGTH(MED_CRMUF)) AS INT) AS VARCHAR) CRM
    , LTRIM(RTRIM(UPPER(collate(COALESCE(MED_NOME, ''), 'en-ci-ai')))) AS MED_NOME
    , LTRIM(RTRIM(UPPER(collate(COALESCE(MED_ESP1, ''), 'en-ci-ai')))) AS MED_ESP1
    , LTRIM(RTRIM(UPPER(collate(COALESCE(MED_ESP2, ''), 'en-ci-ai')))) AS MED_ESP2
    , LTRIM(RTRIM(UPPER(collate(COALESCE(END_LOGRADOURO, ''), 'en-ci-ai')))) AS END_LOGRADOURO
    , LTRIM(RTRIM(UPPER(collate(COALESCE(END_NUMERO, ''), 'en-ci-ai')))) AS END_NUMERO
    , LTRIM(RTRIM(UPPER(collate(COALESCE(END_COMPLEMENTO, ''), 'en-ci-ai')))) AS END_COMPLEMENTO
    , LTRIM(RTRIM(UPPER(collate(COALESCE(END_BAIRRO, ''), 'en-ci-ai')))) AS END_BAIRRO
    , LTRIM(RTRIM(UPPER(collate(COALESCE(END_CIDADE, ''), 'en-ci-ai')))) AS END_CIDADE
    , LTRIM(RTRIM(UPPER(collate(COALESCE(END_CEP, ''), 'en-ci-ai')))) AS END_CEP
    , LTRIM(RTRIM(UPPER(collate(COALESCE(REG_NOME, ''), 'en-ci-ai')))) AS REG_NOME
    , LTRIM(RTRIM(UPPER(collate(COALESCE(MUN_NOME, ''), 'en-ci-ai')))) AS MUN_NOME
    , LTRIM(RTRIM(UPPER(collate(COALESCE(COM_EMAIL, ''), 'en-ci-ai')))) AS COM_EMAIL
    , LTRIM(RTRIM(UPPER(collate(COALESCE(COM_TELEFONE, ''), 'en-ci-ai')))) AS COM_TELEFONE
FROM DB_PX_PROCESS.PUBLIC.CAD_MEDICO_MAESTRO A
WHERE MED_FLAG_ATIVO = 1;
*/





    

--UPDATE DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS A
--SET A.MED_CODIGO_UNICO = B.MED_CODIGO_UNICO
--    , A.MED_CODIGO = B.MED_CODIGO
--    , A.MED_CODIGO_BR = B.MED_CODIGO_BR
--FROM TEMP_MEDICO_MAESTRO AS B
--WHERE A.UF_CRM = B.UF_CRM
--    AND A.CRM = B.CRM;
    
    

INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO(UF_CRM, CRM, IDENT01, IDENT02, IDENT03, IDENT04, IDENT05, FLG_STATUS, ID_PAIS)
SELECT DISTINCT 
    UF_CRM
    , CRM
    , IDENT01
    , IDENT02
    , IDENT03
    , IDENT04
    , IDENT05
    , FALSE AS FLG_STATUS
    , ID_PAIS
FROM TEMP_MEDICO E
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO X WHERE 
    E.UF_CRM = X.UF_CRM
    AND E.CRM = X.CRM
    AND E.IDENT01 = X.IDENT01
    AND E.IDENT02 = X.IDENT02
    AND E.IDENT03 = X.IDENT03
    AND E.IDENT04 = X.IDENT04
    AND E.IDENT05 = X.IDENT05
);

/*
INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO(UF_CRM, CRM, IDENT01, IDENT02, IDENT03, IDENT04, IDENT05, FLG_STATUS, ID_PAIS, MED_CODIGO_UNICO, MED_CODIGO, MED_CODIGO_BR)
SELECT DISTINCT 
    UF_CRM
    , CRM
    , '' IDENT01
    , '' IDENT02
    , '' IDENT03
    , '' IDENT04
    , '' IDENT05
    , TRUE AS FLG_STATUS
    , (SELECT MIN(ID_PAIS) FROM DB_CRM_ANALYTICS.CURATED.DIM_PAIS WHERE PAIS = 'BRASIL') ID_PAIS
    , MED_CODIGO_UNICO
    , MED_CODIGO
    , MED_CODIGO_BR
FROM TEMP_MEDICO_MAESTRO E
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO X WHERE 
    E.UF_CRM = X.UF_CRM
    AND E.CRM = X.CRM
);
*/



INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME(ID_MEDICO, NOME)
SELECT DISTINCT ID_MEDICO, collate(NOME_PROF, 'en-ci-ai') NOME_PROF
FROM TEMP_MEDICO AS A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME X WHERE X.ID_MEDICO = B.ID_MEDICO AND collate(A.NOME_PROF, 'en-ci-ai') = X.NOME);

/*
INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME(ID_MEDICO, NOME)
SELECT DISTINCT ID_MEDICO, collate(A.MED_NOME, 'en-ci-ai') MED_NOME
FROM TEMP_MEDICO_MAESTRO AS A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.MED_CODIGO_UNICO = B.MED_CODIGO_UNICO
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME X WHERE X.ID_MEDICO = B.ID_MEDICO AND collate(A.MED_NOME, 'en-ci-ai') = X.NOME);
*/


INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO(ID_MEDICO, ENDERECO_COMPLETO, PREFIXO_ENDERECO, ENDERECO, BAIRRO, CIDADE, ESTADO, NUMERO_EXTERNO, NUMERO_INTERNO, CODIGO_POSTAL)
SELECT DISTINCT 
    ID_MEDICO
    , ENDERECO_COMPLETO
	, PREFIXO_ENDERECO
	, ENDERECO
	, BAIRRO
	, CIDADE
	, ESTADO
	, NUMERO_EXTERNO
	, NUMERO_INTERNO
	, CODIGO_POSTAL
FROM TEMP_MEDICO AS A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
WHERE 
    A.ENDERECO_COMPLETO != ''
    AND NOT EXISTS (
    SELECT 1 
    FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO X 
    WHERE X.ID_MEDICO = B.ID_MEDICO 
        AND X.PREFIXO_ENDERECO = A.PREFIXO_ENDERECO
        AND X.ENDERECO = A.ENDERECO
        AND X.BAIRRO = A.BAIRRO
        AND X.CIDADE = A.CIDADE
        AND X.ESTADO = A.ESTADO
        AND X.NUMERO_EXTERNO = A.NUMERO_EXTERNO
        AND X.NUMERO_INTERNO = A.NUMERO_INTERNO
        AND X.CODIGO_POSTAL = A.CODIGO_POSTAL
);



/*
INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO(ID_MEDICO, ENDERECO_COMPLETO, PREFIXO_ENDERECO, ENDERECO, BAIRRO, CIDADE, ESTADO, NUMERO_EXTERNO, NUMERO_INTERNO, CODIGO_POSTAL)
SELECT DISTINCT 
    ID_MEDICO
    , (END_LOGRADOURO || ' ' || END_NUMERO || ', ' || MUN_NOME) AS ENDERECO_COMPLETO
	, '' PREFIXO_ENDERECO
	, END_LOGRADOURO AS ENDERECO
	, END_BAIRRO AS BAIRRO
	, MUN_NOME AS CIDADE
	, '' ESTADO
	, END_NUMERO AS NUMERO_EXTERNO
	, END_COMPLEMENTO AS NUMERO_INTERNO
	, END_CEP  AS CODIGO_POSTAL    
FROM TEMP_MEDICO_MAESTRO AS A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.MED_CODIGO_UNICO = B.MED_CODIGO_UNICO
WHERE 
    NOT EXISTS (
    SELECT 1 
    FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO X 
    WHERE X.ID_MEDICO = B.ID_MEDICO 
        AND X.ENDERECO = A.END_LOGRADOURO
        AND X.BAIRRO = A.END_BAIRRO
        AND X.CIDADE = A.MUN_NOME
        AND X.NUMERO_EXTERNO = A.END_NUMERO
        AND X.NUMERO_INTERNO = A.END_COMPLEMENTO
        AND X.CODIGO_POSTAL = A.END_CEP
);
*/






INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE(ID_MEDICO, ID_ESPECIALIDADE)
SELECT DISTINCT B.ID_MEDICO, D.ID_ESPECIALIDADE
FROM TEMP_MEDICO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
INNER JOIN DB_CRM_ANALYTICS.CURATED.FATO_ESPECIALIDADE_DE_PARA_BRASIL C ON A.COD_ESPEC_PROF1 = C.ESPECIALIDADE_DE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON C.ESPECIALIDADE_PARA = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
WHERE E.PAIS = 'BRASIL'
    AND NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE X WHERE B.ID_MEDICO = X.ID_MEDICO AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE);


INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE(ID_MEDICO, ID_ESPECIALIDADE)
SELECT DISTINCT B.ID_MEDICO, D.ID_ESPECIALIDADE
FROM TEMP_MEDICO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
INNER JOIN DB_CRM_ANALYTICS.CURATED.FATO_ESPECIALIDADE_DE_PARA_BRASIL C ON A.ESPEC_PROF1 = C.ESPECIALIDADE_DE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON C.ESPECIALIDADE_PARA = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
WHERE E.PAIS = 'BRASIL'
    AND NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE X WHERE B.ID_MEDICO = X.ID_MEDICO AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE);



INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE(ID_MEDICO, ID_ESPECIALIDADE)
SELECT DISTINCT B.ID_MEDICO, D.ID_ESPECIALIDADE
FROM TEMP_MEDICO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
INNER JOIN DB_CRM_ANALYTICS.CURATED.FATO_ESPECIALIDADE_DE_PARA_BRASIL C ON A.COD_ESPEC_PROF2 = C.ESPECIALIDADE_DE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON C.ESPECIALIDADE_PARA = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
WHERE E.PAIS = 'BRASIL'
    AND NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE X WHERE B.ID_MEDICO = X.ID_MEDICO AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE);


INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE(ID_MEDICO, ID_ESPECIALIDADE)
SELECT DISTINCT B.ID_MEDICO, D.ID_ESPECIALIDADE
FROM TEMP_MEDICO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
INNER JOIN DB_CRM_ANALYTICS.CURATED.FATO_ESPECIALIDADE_DE_PARA_BRASIL C ON A.ESPEC_PROF2 = C.ESPECIALIDADE_DE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON C.ESPECIALIDADE_PARA = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
WHERE E.PAIS = 'BRASIL'
    AND NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE X WHERE B.ID_MEDICO = X.ID_MEDICO AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE);


/*
INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE(ID_MEDICO, ID_ESPECIALIDADE)
SELECT DISTINCT B.ID_MEDICO, D.ID_ESPECIALIDADE
FROM TEMP_MEDICO_MAESTRO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.MED_CODIGO_UNICO = B.MED_CODIGO_UNICO
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON A.MED_ESP1 = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON E.PAIS = 'BRASIL'
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE X WHERE B.ID_MEDICO = X.ID_MEDICO AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE);
*/

/*
INSERT INTO DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE(ID_MEDICO, ID_ESPECIALIDADE)
SELECT DISTINCT B.ID_MEDICO, D.ID_ESPECIALIDADE
FROM TEMP_MEDICO_MAESTRO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.MED_CODIGO_UNICO = B.MED_CODIGO_UNICO
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON A.MED_ESP2 = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON E.PAIS = 'BRASIL'
WHERE NOT EXISTS (SELECT 1 FROM DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ESPECIALIDADE X WHERE B.ID_MEDICO = X.ID_MEDICO AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE);
*/

TRUNCATE TABLE DB_CRM_ANALYTICS.CURATED.FATO_PAINEL;


INSERT INTO DB_CRM_ANALYTICS.CURATED.FATO_PAINEL(ID_MEDICO, ID_ESPECIALIDADE, ID_FORCAVENDAS, STATUS, ID_LABORATORIO, ID_PAIS, DATA_INCLUSAO, CODIGO_INTERNO, ID_MEDICO_NOME, VISITADO_3_MESES, VISITADO_6_MESES, VISITADO_12_MESES, VISITADO, VISITADO_1_MESES, ID_MEDICO_ENDERECO, COD_ESPEC_PROF, ESPEC_PROF, TELEFONE, EMAIL)  
SELECT B.ID_MEDICO, D.ID_ESPECIALIDADE, F.ID_FORCAVENDAS, 
    CASE WHEN F.ID_FORCAVENDAS IS NULL OR A.SETOR_HISTORICO = TRUE OR F.SETOR_VAGO = TRUE THEN FALSE ELSE A.FLG_STATUS END STATUS
    , A.ID_LABORATORIO, A.ID_PAIS, MIN(A.DATA_INCLUSAO) AS DATA_INCLUSAO, A.PROF_ID, NOME.ID_MEDICO_NOME, FALSE VISITADO_3_MESES, FALSE VISITADO_6_MESES, FALSE VISITADO_12_MESES, FALSE VISITADO, FALSE VISITADO_1_MESES, ENDERECO.ID_MEDICO_ENDERECO, A.COD_ESPEC_PROF1 COD_ESPEC_PROF, A.ESPEC_PROF1 ESPEC_PROF, A.CELULAR, A.EMAIL
FROM TEMP_MEDICO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
INNER JOIN DB_CRM_ANALYTICS.CURATED.FATO_ESPECIALIDADE_DE_PARA_BRASIL C ON A.COD_ESPEC_PROF1 = C.ESPECIALIDADE_DE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON C.ESPECIALIDADE_PARA = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS F ON A.ID_LABORATORIO = F.ID_LABORATORIO AND A.SETOR = F.SETOR
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME NOME ON B.ID_MEDICO = NOME.ID_MEDICO AND collate(A.NOME_PROF, 'en-ci-ai') = NOME.NOME
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO ENDERECO ON 
    B.ID_MEDICO = ENDERECO.ID_MEDICO
    AND ENDERECO.PREFIXO_ENDERECO = A.PREFIXO_ENDERECO
    AND ENDERECO.ENDERECO = A.ENDERECO
    AND ENDERECO.BAIRRO = A.BAIRRO
    AND ENDERECO.CIDADE = A.CIDADE
    AND ENDERECO.ESTADO = A.ESTADO
    AND ENDERECO.NUMERO_EXTERNO = A.NUMERO_EXTERNO
    AND ENDERECO.NUMERO_INTERNO = A.NUMERO_INTERNO
    AND ENDERECO.CODIGO_POSTAL = A.CODIGO_POSTAL
WHERE E.PAIS = 'BRASIL'
    AND NOT EXISTS (
        SELECT 1 
        FROM DB_CRM_ANALYTICS.CURATED.FATO_PAINEL X 
        WHERE B.ID_MEDICO = X.ID_MEDICO 
            AND COALESCE(X.ID_FORCAVENDAS, 0) = COALESCE(F.ID_FORCAVENDAS, 0) 
            AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE
            AND X.ID_LABORATORIO = A.ID_LABORATORIO 
            AND X.ID_PAIS = A.ID_PAIS)
GROUP BY B.ID_MEDICO, D.ID_ESPECIALIDADE, F.ID_FORCAVENDAS, A.SETOR_HISTORICO, F.SETOR_VAGO, A.FLG_STATUS, A.ID_LABORATORIO, A.ID_PAIS, A.PROF_ID, NOME.ID_MEDICO_NOME, ENDERECO.ID_MEDICO_ENDERECO, A.COD_ESPEC_PROF1, A.ESPEC_PROF1, A.CELULAR, A.EMAIL;



INSERT INTO DB_CRM_ANALYTICS.CURATED.FATO_PAINEL(ID_MEDICO, ID_ESPECIALIDADE, ID_FORCAVENDAS, STATUS, ID_LABORATORIO, ID_PAIS, DATA_INCLUSAO, CODIGO_INTERNO, ID_MEDICO_NOME, VISITADO_3_MESES, VISITADO_6_MESES, VISITADO_12_MESES, VISITADO, VISITADO_1_MESES, ID_MEDICO_ENDERECO, COD_ESPEC_PROF, ESPEC_PROF, TELEFONE, EMAIL)  
SELECT B.ID_MEDICO, D.ID_ESPECIALIDADE, F.ID_FORCAVENDAS, 
    CASE WHEN F.ID_FORCAVENDAS IS NULL OR A.SETOR_HISTORICO = TRUE OR F.SETOR_VAGO = TRUE THEN FALSE ELSE A.FLG_STATUS END STATUS
    , A.ID_LABORATORIO, A.ID_PAIS, MIN(A.DATA_INCLUSAO) AS DATA_INCLUSAO, A.PROF_ID, NOME.ID_MEDICO_NOME, FALSE VISITADO_3_MESES, FALSE VISITADO_6_MESES, FALSE VISITADO_12_MESES, FALSE VISITADO, FALSE VISITADO_1_MESES, ENDERECO.ID_MEDICO_ENDERECO, A.COD_ESPEC_PROF1 COD_ESPEC_PROF, A.ESPEC_PROF1 ESPEC_PROF, A.CELULAR, A.EMAIL
FROM TEMP_MEDICO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
INNER JOIN DB_CRM_ANALYTICS.CURATED.FATO_ESPECIALIDADE_DE_PARA_BRASIL C ON A.ESPEC_PROF1 = C.ESPECIALIDADE_DE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON C.ESPECIALIDADE_PARA = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS F ON A.ID_LABORATORIO = F.ID_LABORATORIO AND A.SETOR = F.SETOR
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME NOME ON B.ID_MEDICO = NOME.ID_MEDICO AND collate(A.NOME_PROF, 'en-ci-ai') = NOME.NOME
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO ENDERECO ON B.ID_MEDICO = ENDERECO.ID_MEDICO 
    AND ENDERECO.PREFIXO_ENDERECO = A.PREFIXO_ENDERECO
    AND ENDERECO.ENDERECO = A.ENDERECO
    AND ENDERECO.BAIRRO = A.BAIRRO
    AND ENDERECO.CIDADE = A.CIDADE
    AND ENDERECO.ESTADO = A.ESTADO
    AND ENDERECO.NUMERO_EXTERNO = A.NUMERO_EXTERNO
    AND ENDERECO.NUMERO_INTERNO = A.NUMERO_INTERNO
    AND ENDERECO.CODIGO_POSTAL = A.CODIGO_POSTAL
WHERE E.PAIS = 'BRASIL'
    AND NOT EXISTS (
        SELECT 1 
        FROM DB_CRM_ANALYTICS.CURATED.FATO_PAINEL X 
        WHERE B.ID_MEDICO = X.ID_MEDICO 
            AND COALESCE(X.ID_FORCAVENDAS, 0) = COALESCE(F.ID_FORCAVENDAS, 0) 
            AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE
            AND X.ID_LABORATORIO = A.ID_LABORATORIO 
            AND X.ID_PAIS = A.ID_PAIS)
GROUP BY B.ID_MEDICO, D.ID_ESPECIALIDADE, F.ID_FORCAVENDAS, A.SETOR_HISTORICO, F.SETOR_VAGO, A.FLG_STATUS, A.ID_LABORATORIO, A.ID_PAIS, A.PROF_ID, NOME.ID_MEDICO_NOME, ENDERECO.ID_MEDICO_ENDERECO, A.COD_ESPEC_PROF1, A.ESPEC_PROF1, A.CELULAR, A.EMAIL;


INSERT INTO DB_CRM_ANALYTICS.CURATED.FATO_PAINEL(ID_MEDICO, ID_ESPECIALIDADE, ID_FORCAVENDAS, STATUS, ID_LABORATORIO, ID_PAIS, DATA_INCLUSAO, CODIGO_INTERNO, ID_MEDICO_NOME, VISITADO_3_MESES, VISITADO_6_MESES, VISITADO_12_MESES, VISITADO, VISITADO_1_MESES, ID_MEDICO_ENDERECO, COD_ESPEC_PROF, ESPEC_PROF, TELEFONE, EMAIL)  
SELECT B.ID_MEDICO, D.ID_ESPECIALIDADE, F.ID_FORCAVENDAS, 
    CASE WHEN F.ID_FORCAVENDAS IS NULL OR A.SETOR_HISTORICO = TRUE OR F.SETOR_VAGO = TRUE THEN FALSE ELSE A.FLG_STATUS END STATUS
    , A.ID_LABORATORIO, A.ID_PAIS, MIN(A.DATA_INCLUSAO) AS DATA_INCLUSAO, A.PROF_ID, NOME.ID_MEDICO_NOME, FALSE VISITADO_3_MESES, FALSE VISITADO_6_MESES, FALSE VISITADO_12_MESES, FALSE VISITADO, FALSE VISITADO_1_MESES, ENDERECO.ID_MEDICO_ENDERECO, A.COD_ESPEC_PROF1 COD_ESPEC_PROF, A.ESPEC_PROF1 ESPEC_PROF, A.CELULAR, A.EMAIL
FROM TEMP_MEDICO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON $$N/A$$ = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS F ON A.ID_LABORATORIO = F.ID_LABORATORIO AND A.SETOR = F.SETOR
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME NOME ON B.ID_MEDICO = NOME.ID_MEDICO AND collate(A.NOME_PROF, 'en-ci-ai') = NOME.NOME
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO ENDERECO 
    ON B.ID_MEDICO = ENDERECO.ID_MEDICO 
    AND ENDERECO.PREFIXO_ENDERECO = A.PREFIXO_ENDERECO
    AND ENDERECO.ENDERECO = A.ENDERECO
    AND ENDERECO.BAIRRO = A.BAIRRO
    AND ENDERECO.CIDADE = A.CIDADE
    AND ENDERECO.ESTADO = A.ESTADO
    AND ENDERECO.NUMERO_EXTERNO = A.NUMERO_EXTERNO
    AND ENDERECO.NUMERO_INTERNO = A.NUMERO_INTERNO
    AND ENDERECO.CODIGO_POSTAL = A.CODIGO_POSTAL
WHERE E.PAIS = 'BRASIL'
    AND NOT EXISTS (
        SELECT 1 
        FROM DB_CRM_ANALYTICS.CURATED.FATO_PAINEL X 
        WHERE B.ID_MEDICO = X.ID_MEDICO 
            AND COALESCE(X.ID_FORCAVENDAS, 0) = COALESCE(F.ID_FORCAVENDAS, 0) 
            AND X.ID_LABORATORIO = A.ID_LABORATORIO 
            AND X.ID_PAIS = A.ID_PAIS)
GROUP BY B.ID_MEDICO, D.ID_ESPECIALIDADE, F.ID_FORCAVENDAS, A.SETOR_HISTORICO, F.SETOR_VAGO, A.FLG_STATUS, A.ID_LABORATORIO, A.ID_PAIS, A.PROF_ID, NOME.ID_MEDICO_NOME, ENDERECO.ID_MEDICO_ENDERECO, A.COD_ESPEC_PROF1, A.ESPEC_PROF1, A.CELULAR, A.EMAIL;




INSERT INTO DB_CRM_ANALYTICS.CURATED.FATO_PAINEL(ID_MEDICO, ID_ESPECIALIDADE, ID_FORCAVENDAS, STATUS, ID_LABORATORIO, ID_PAIS, DATA_INCLUSAO, CODIGO_INTERNO, ID_MEDICO_NOME, VISITADO_3_MESES, VISITADO_6_MESES, VISITADO_12_MESES, VISITADO, VISITADO_1_MESES, ID_MEDICO_ENDERECO, COD_ESPEC_PROF, ESPEC_PROF, TELEFONE, EMAIL)  
SELECT B.ID_MEDICO, D.ID_ESPECIALIDADE, F.ID_FORCAVENDAS, 
    CASE WHEN F.ID_FORCAVENDAS IS NULL OR A.SETOR_HISTORICO = TRUE OR F.SETOR_VAGO = TRUE THEN FALSE ELSE A.FLG_STATUS END STATUS
    , A.ID_LABORATORIO, A.ID_PAIS, MIN(A.DATA_INCLUSAO) AS DATA_INCLUSAO, A.PROF_ID, NOME.ID_MEDICO_NOME, FALSE VISITADO_3_MESES, FALSE VISITADO_6_MESES, FALSE VISITADO_12_MESES, FALSE VISITADO, FALSE VISITADO_1_MESES, ENDERECO.ID_MEDICO_ENDERECO, A.COD_ESPEC_PROF1 COD_ESPEC_PROF, A.ESPEC_PROF1 ESPEC_PROF, A.CELULAR, A.EMAIL
FROM TEMP_MEDICO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.UF_CRM = B.UF_CRM
    AND A.CRM = B.CRM
    AND A.IDENT01 = B.IDENT01
    AND A.IDENT02 = B.IDENT02
    AND A.IDENT03 = B.IDENT03
    AND A.IDENT04 = B.IDENT04
    AND A.IDENT05 = B.IDENT05
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON $$N/A$$ = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS F ON A.ID_LABORATORIO = F.ID_LABORATORIO AND A.SETOR = F.SETOR
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME NOME ON B.ID_MEDICO = NOME.ID_MEDICO AND collate(A.NOME_PROF, 'en-ci-ai') = NOME.NOME
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO ENDERECO 
    ON B.ID_MEDICO = ENDERECO.ID_MEDICO 
    AND ENDERECO.PREFIXO_ENDERECO = A.PREFIXO_ENDERECO
    AND ENDERECO.ENDERECO = A.ENDERECO
    AND ENDERECO.BAIRRO = A.BAIRRO
    AND ENDERECO.CIDADE = A.CIDADE
    AND ENDERECO.ESTADO = A.ESTADO
    AND ENDERECO.NUMERO_EXTERNO = A.NUMERO_EXTERNO
    AND ENDERECO.NUMERO_INTERNO = A.NUMERO_INTERNO
    AND ENDERECO.CODIGO_POSTAL = A.CODIGO_POSTAL
WHERE E.PAIS = 'PARAGUAI'
    AND NOT EXISTS (
        SELECT 1 
        FROM DB_CRM_ANALYTICS.CURATED.FATO_PAINEL X 
        WHERE B.ID_MEDICO = X.ID_MEDICO 
            AND COALESCE(X.ID_FORCAVENDAS, 0) = COALESCE(F.ID_FORCAVENDAS, 0) 
            AND X.ID_LABORATORIO = A.ID_LABORATORIO 
            AND X.ID_PAIS = A.ID_PAIS)
GROUP BY B.ID_MEDICO, D.ID_ESPECIALIDADE, F.ID_FORCAVENDAS, A.SETOR_HISTORICO, F.SETOR_VAGO, A.FLG_STATUS, A.ID_LABORATORIO, A.ID_PAIS, A.PROF_ID, NOME.ID_MEDICO_NOME, ENDERECO.ID_MEDICO_ENDERECO, A.COD_ESPEC_PROF1, A.ESPEC_PROF1, A.CELULAR, A.EMAIL;




UPDATE DB_CRM_ANALYTICS.CURATED.DIM_MEDICO SET FLG_STATUS = FALSE;

UPDATE DB_CRM_ANALYTICS.CURATED.DIM_MEDICO X SET X.FLG_STATUS = TRUE
FROM DB_CRM_ANALYTICS.CURATED.FATO_PAINEL E 
WHERE E.ID_MEDICO = X.ID_MEDICO
    AND E.STATUS = TRUE;

/*
INSERT INTO DB_CRM_ANALYTICS.CURATED.FATO_PAINEL(ID_MEDICO, ID_ESPECIALIDADE, ID_FORCAVENDAS, STATUS, ID_LABORATORIO, ID_PAIS, DATA_INCLUSAO, CODIGO_INTERNO, ID_MEDICO_NOME, VISITADO_3_MESES, VISITADO_6_MESES, VISITADO_12_MESES, VISITADO, VISITADO_1_MESES, ID_MEDICO_ENDERECO, COD_ESPEC_PROF, ESPEC_PROF, TELEFONE, EMAIL)  
SELECT DISTINCT B.ID_MEDICO, D.ID_ESPECIALIDADE, NULL ID_FORCAVENDAS, 
    TRUE STATUS
    , 9999 ID_LABORATORIO, 1 ID_PAIS, NULL AS DATA_INCLUSAO, NULL PROF_ID, NOME.ID_MEDICO_NOME, FALSE VISITADO_3_MESES, FALSE VISITADO_6_MESES, FALSE VISITADO_12_MESES, FALSE VISITADO, FALSE VISITADO_1_MESES, ENDERECO.ID_MEDICO_ENDERECO, NULL COD_ESPEC_PROF, NULL ESPEC_PROF, A.COM_TELEFONE, A.COM_EMAIL
FROM TEMP_MEDICO_MAESTRO A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS B
    ON A.MED_CODIGO_UNICO = B.MED_CODIGO_UNICO
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_ESPECIALIDADE D ON A.MED_ESP1 = D.ESPECIALIDADE
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_PAIS E ON E.PAIS = 'BRASIL'
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_NOME NOME ON B.ID_MEDICO = NOME.ID_MEDICO AND collate(A.MED_NOME, 'en-ci-ai') = NOME.NOME
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO_ENDERECO ENDERECO ON 
    B.ID_MEDICO = ENDERECO.ID_MEDICO
    AND ENDERECO.ENDERECO = A.END_LOGRADOURO
    AND ENDERECO.BAIRRO = A.END_BAIRRO
    AND ENDERECO.CIDADE = A.MUN_NOME
    AND ENDERECO.NUMERO_EXTERNO = A.END_NUMERO 
    AND ENDERECO.NUMERO_INTERNO = A.END_COMPLEMENTO
    AND ENDERECO.CODIGO_POSTAL = A.END_CEP
WHERE E.PAIS = 'BRASIL'
    AND NOT EXISTS (
        SELECT 1 
        FROM DB_CRM_ANALYTICS.CURATED.FATO_PAINEL X 
        WHERE B.ID_MEDICO = X.ID_MEDICO 
            AND X.ID_ESPECIALIDADE = D.ID_ESPECIALIDADE
            AND X.ID_LABORATORIO = 9999
            AND X.ID_PAIS = 1);
*/

INSERT INTO DB_CRM_ANALYTICS.CURATED.FATO_VISITAS(ID_MEDICO, ID_FORCAVENDAS, DATA_DA_VISITA, COD_TIPO_VISITA, COD_MOTNVIS, FLG_VISITA_EFETIVA, ID_PAIS, ID_LABORATORIO, CICLO, CODIGO_INTERNO)
SELECT DISTINCT E.ID_MEDICO, G.ID_FORCAVENDAS, C.DT_VISITA, C.COD_TIPO_VISITA, C.COD_MOTNVIS, C.FLG_VISITA_EFETIVA, E.ID_PAIS, D.ID_LABORATORIO, H.CICLO, D.PROF_ID
FROM DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO B ON A.NM_CLIENTE = B.LABORATORIO
INNER JOIN DB_CRM_SALES_FARMA_DEV.CURATED.FAT_VISITAPROF C ON A.NMBANCO = C.ORIGEM 
INNER JOIN TEMP_MEDICO D ON B.ID_LABORATORIO = D.ID_LABORATORIO AND C.PROF_ID = D.PROF_ID
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS E
    ON D.UF_CRM = E.UF_CRM
    AND D.CRM = E.CRM
    AND D.IDENT01 = E.IDENT01
    AND D.IDENT02 = E.IDENT02
    AND D.IDENT03 = E.IDENT03
    AND D.IDENT04 = E.IDENT04
    AND D.IDENT05 = E.IDENT05
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS G ON D.ID_LABORATORIO = G.ID_LABORATORIO AND D.SETOR = G.SETOR
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_CALENDARIO H ON A.NMBANCO = H.ORIGEM AND C.CIA = H.CIA AND C.EQUIPE = H.EQUIPE AND C.DT_VISITA BETWEEN H.DT_INICIAL AND H.DT_FINAL
WHERE C.DT_VISITA >= DATEADD (YEAR, -6, CURRENT_DATE)
    AND NOT EXISTS (
        SELECT 1
        FROM DB_CRM_ANALYTICS.CURATED.FATO_VISITAS X
        WHERE X.ID_MEDICO = E.ID_MEDICO
            AND X.ID_FORCAVENDAS = G.ID_FORCAVENDAS
            AND X.DATA_DA_VISITA = C.DT_VISITA
            AND X.FLG_VISITA_EFETIVA = C.FLG_VISITA_EFETIVA
            AND X.ID_PAIS = E.ID_PAIS
            AND X.ID_LABORATORIO = D.ID_LABORATORIO
    );



INSERT INTO DB_CRM_ANALYTICS.CURATED.FATO_VISITAS(ID_MEDICO, ID_FORCAVENDAS, DATA_DA_VISITA, COD_TIPO_VISITA, COD_MOTNVIS, FLG_VISITA_EFETIVA, ID_PAIS, ID_LABORATORIO, CICLO, CODIGO_INTERNO)
SELECT DISTINCT E.ID_MEDICO, G.ID_FORCAVENDAS, C.DT_VISITA, C.COD_TIPO_VISITA, C.COD_MOTNVIS, C.FLG_VISITA_EFETIVA, E.ID_PAIS, D.ID_LABORATORIO, H.CICLO, D.PROF_ID
FROM DB_CRM_SALES_FARMA_DEV.CONTROL.CTL_TB_DATABASES A
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_LABORATORIO B ON A.NM_CLIENTE = B.LABORATORIO
INNER JOIN DB_CRM_SALES_FARMA_DEV.CURATED.FAT_VISITAPROF C ON A.NMBANCO = C.ORIGEM 
INNER JOIN TEMP_MEDICO D ON B.ID_LABORATORIO = D.ID_LABORATORIO AND C.PROF_ID = D.PROF_ID
INNER JOIN DB_CRM_ANALYTICS.CURATED.DIM_MEDICO AS E
    ON D.UF_CRM = E.UF_CRM
    AND D.CRM = E.CRM
    AND D.IDENT01 = E.IDENT01
    AND D.IDENT02 = E.IDENT02
    AND D.IDENT03 = E.IDENT03
    AND D.IDENT04 = E.IDENT04
    AND D.IDENT05 = E.IDENT05
LEFT JOIN DB_CRM_ANALYTICS.CURATED.DIM_FORCAVENDAS G ON D.ID_LABORATORIO = G.ID_LABORATORIO AND D.SETOR = G.SETOR
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_CALENDARIO H ON A.NMBANCO = H.ORIGEM AND C.CIA = H.CIA AND C.EQUIPE = H.EQUIPE AND C.DT_VISITA BETWEEN H.DT_INICIAL AND H.DT_FINAL
WHERE C.DT_VISITA >= DATEADD (YEAR, -6, CURRENT_DATE)
    AND G.ID_FORCAVENDAS IS NULL
    AND NOT EXISTS (
        SELECT 1
        FROM DB_CRM_ANALYTICS.CURATED.FATO_VISITAS X
        WHERE X.ID_MEDICO = E.ID_MEDICO
            AND X.DATA_DA_VISITA = C.DT_VISITA
            AND X.FLG_VISITA_EFETIVA = C.FLG_VISITA_EFETIVA
            AND X.ID_PAIS = E.ID_PAIS
            AND X.ID_LABORATORIO = D.ID_LABORATORIO
    );


UPDATE
  DB_CRM_ANALYTICS.CURATED.FATO_PAINEL AS A
SET
  A.VISITADO_1_MESES = TRUE
FROM
  (
    SELECT
      ID_LABORATORIO,
      CODIGO_INTERNO
    FROM
      DB_CRM_ANALYTICS.CURATED.FATO_VISITAS
    WHERE
      FLG_VISITA_EFETIVA = TRUE
      AND DATA_DA_VISITA >= DATEADD (MONTH, -1, CURRENT_DATE)
    GROUP BY
      ID_LABORATORIO,
      CODIGO_INTERNO
  ) AS B
WHERE
  A.ID_LABORATORIO = B.ID_LABORATORIO
  AND A.CODIGO_INTERNO = B.CODIGO_INTERNO;
    

UPDATE
  DB_CRM_ANALYTICS.CURATED.FATO_PAINEL AS A
SET
  A.VISITADO_3_MESES = TRUE
FROM
  (
    SELECT
      ID_LABORATORIO,
      CODIGO_INTERNO
    FROM
      DB_CRM_ANALYTICS.CURATED.FATO_VISITAS
    WHERE
      FLG_VISITA_EFETIVA = TRUE
      AND DATA_DA_VISITA >= DATEADD (MONTH, -3, CURRENT_DATE)
    GROUP BY
      ID_LABORATORIO,
      CODIGO_INTERNO
  ) AS B
WHERE
  A.ID_LABORATORIO = B.ID_LABORATORIO
  AND A.CODIGO_INTERNO = B.CODIGO_INTERNO;



UPDATE
  DB_CRM_ANALYTICS.CURATED.FATO_PAINEL AS A
SET
  A.VISITADO_6_MESES = TRUE
FROM
  (
    SELECT
      ID_LABORATORIO,
      CODIGO_INTERNO
    FROM
      DB_CRM_ANALYTICS.CURATED.FATO_VISITAS
    WHERE
      FLG_VISITA_EFETIVA = TRUE
      AND DATA_DA_VISITA >= DATEADD (MONTH, -6, CURRENT_DATE)
    GROUP BY
      ID_LABORATORIO,
      CODIGO_INTERNO
  ) AS B
WHERE
  A.ID_LABORATORIO = B.ID_LABORATORIO
  AND A.CODIGO_INTERNO = B.CODIGO_INTERNO;



UPDATE
  DB_CRM_ANALYTICS.CURATED.FATO_PAINEL AS A
SET
  A.VISITADO_12_MESES = TRUE
FROM
  (
    SELECT
      ID_LABORATORIO,
      CODIGO_INTERNO
    FROM
      DB_CRM_ANALYTICS.CURATED.FATO_VISITAS
    WHERE
      FLG_VISITA_EFETIVA = TRUE
      AND DATA_DA_VISITA >= DATEADD (YEAR, -1, CURRENT_DATE)
    GROUP BY
      ID_LABORATORIO,
      CODIGO_INTERNO
  ) AS B
WHERE
  A.ID_LABORATORIO = B.ID_LABORATORIO
  AND A.CODIGO_INTERNO = B.CODIGO_INTERNO;



UPDATE
  DB_CRM_ANALYTICS.CURATED.FATO_PAINEL AS A
SET
  A.VISITADO = TRUE
FROM
  (
    SELECT
      ID_LABORATORIO,
      CODIGO_INTERNO
    FROM
      DB_CRM_ANALYTICS.CURATED.FATO_VISITAS
    WHERE
      FLG_VISITA_EFETIVA = TRUE
      AND DATA_DA_VISITA >= DATEADD (YEAR, -5, CURRENT_DATE)
    GROUP BY
      ID_LABORATORIO,
      CODIGO_INTERNO
  ) AS B
WHERE
  A.ID_LABORATORIO = B.ID_LABORATORIO
  AND A.CODIGO_INTERNO = B.CODIGO_INTERNO;



create or replace view DB_CRM_SALES_FARMA_DEV.VIEW.FF_RX_CADASTRO(
	CIA,
	EQUIPE,
	EQUIPE_DESCRICAO,
	REGIONAL,
	SETOR,
	COD_REG,
	UF_REG,
	NOME,
	ANIVERSARIO,
	SEXO,
	EMAIL,
	SIGLA_PRIMEIRA_ESPECIALIDADE,
	SIGLA_SEGUNDA_ESPECIALIDADE,
	FREQUENCIA,
	SEMANA,
	ROTEIRO,
	TURNO,
	SEQUENCIA,
	LOCAL_TRABALHO,
	TIPO_LOGRAD,
	ENDERECO,
	NUMERO,
	COMPLEMENTO,
	CEP,
	BAIRRO,
	MUNICIPIO,
	ESTADO,
	DDD,
	TELEF1,
	RAMAL1,
	TELEF2,
	RAMAL2,
	TELEF3,
	RAMAL3,
	PROF_ID,
	ESTAB_ID,
	LOCAL_ID,
	CPF,
	DSC_PRIMEIRA_ESPECIALIDADE,
	DSC_SEGUNDA_ESPECIALIDADE,
	CELULAR,
	ANO_DE_FORMATURA,
	NOME_DA_SECRETARIA,
	ANIVERSARIO_DA_SECRETARIA,
	POSSUI_TERMO_AG,
	VALIDADE_DO_TERMO_AG,
	CLASSIFICACAO,
	OBSERVACAO,
	ELEGIVEL,
	FLG_INTERACAO_GOV,
	LIDER_DE_OPINIAO,
	ESTRATEGIA,
	DATA_INCLUSAO,
	FREQ_NUMERICA,
	POTENCIAL,
	CODIGO_BRICK,
	BRICK,
	TIPO_BRICK,
	SETOR_CLIENTE,
	COD_CATEGORIA,
	CATEGORIA,
	MEDICO_VIP,
	DT_ATIVACAO,
	DIAS_SEM_VISITA,
	DT_ULTIMA_VISITA,
	ORIGEM,
	DT_LAKE
) as
WITH TERMO AS (
    SELECT ORIGEM,CRM, UF_CRM, LETRA, MAX(DT_VALIDADE) AS DT_VALIDADE
    FROM DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GD_N_TERMO_AG
    WHERE STATUS_TERMO = TRUE
    GROUP BY ORIGEM, CRM, UF_CRM, LETRA
    HAVING MAX(DT_VALIDADE) >= CURRENT_DATE
),
DI AS (
    SELECT A.ORIGEM, A.PROF_ID
    , COALESCE(TO_CHAR (DATEDIFF (DAY, MAX(A.DT_VISITA), CURRENT_DATE)),'Não Visitado') AS DIAS_SEM_VISITA
    , MAX(A.DT_VISITA) DT_VISITA
    FROM DB_CRM_SALES_FARMA_DEV.curated.fat_visitaprof AS A
    INNER JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDMEDREP AS B ON A.ORIGEM = B.ORIGEM AND A.PROF_ID = B.PROF_ID
    WHERE B.FLG_ATIVO = TRUE
        AND FLG_VISITA_EFETIVA = TRUE
    GROUP BY A.ORIGEM, A.PROF_ID
)
SELECT
    R.CIA AS CIA
    , R.EQUIPE AS EQUIPE
    , EQUIPE.EQUI_DESCRICAO AS EQUIPE_DESCRICAO
    , R.REGIONAL AS REGIONAL
    , R.EQZ AS SETOR
    , A.CRM AS COD_REG
    , A.UF_CRM AS UF_REG
    , A.NOME_PROF AS NOME
    , IFNULL (RIGHT(TO_VARCHAR(REPLACE(A.DTNASC_PROF, '/', '')),2) || '/' || LEFT(TO_VARCHAR(REPLACE(A.DTNASC_PROF, '/', '')),2) , 'NULL' ) AS ANIVERSARIO
    , A.SEXO AS SEXO
    , REPLACE(REPLACE(A.EMAIL, CHAR(13), ' '), CHAR(10), ' ') AS EMAIL
    , A.COD_ESPEC AS SIGLA_PRIMEIRA_ESPECIALIDADE
    , A.COD_ESPEC AS SIGLA_SEGUNDA_ESPECIALIDADE
    , A.COD_FREQ_PROF AS FREQUENCIA
    , '' AS SEMANA
    , '' AS ROTEIRO
    , '' AS TURNO
    , '' AS SEQUENCIA
    , D.DESCRICAO AS LOCAL_TRABALHO
    , C.PREFIXO_ENDERECO AS TIPO_LOGRAD
    , C.ENDERECO AS ENDERECO
    , C.NUMERO_EXTERNO AS NUMERO
    , C.NUMERO_INTERNO AS COMPLEMENTO
    , LPAD(COALESCE(C.CODIGO_POSTAL, ''), 8, '0') AS CEP
    , C.BAIRRO AS BAIRRO
    , C.CIDADE AS MUNICIPIO
    , C.ESTADO AS ESTADO
    , C.PREFIXO_TELEFONE AS DDD
    , C.TELEFONE1 AS TELEF1
    , '' AS RAMAL1
    , C.TELEFONE2 AS TELEF2
    , '' AS RAMAL2
    , C.TELEFONE3 AS TELEF3
    , '' AS RAMAL3
    , COALESCE(A.PROF_ID , 0) AS PROF_ID
    , COALESCE(B.ESTAB_ID , 0) AS ESTAB_ID
    , B.VIS_LOCAL_ID AS LOCAL_ID
    , LPAD (COALESCE(A.CPF, ''), 11, '0') AS CPF
    , EA.DESCRICAO AS DSC_PRIMEIRA_ESPECIALIDADE
    , EB.DESCRICAO AS DSC_SEGUNDA_ESPECIALIDADE
    , A.CELULAR AS CELULAR
    , A.FORMATURA AS ANO_DE_FORMATURA
    , REPLACE(REPLACE(A.NOMESECRE, CHAR(13), ' '), CHAR(10), ' ') AS NOME_DA_SECRETARIA
    , NULLIF(CONCAT(SUBSTRING(DIANASCT::VARCHAR,3,2), '/', SUBSTRING(DIANASCT::VARCHAR,1,2)), 'NULL') AS ANIVERSARIO_DA_SECRETARIA
    , CASE IFNULL(TERMO.CRM, 'N') WHEN 'N' THEN 'N' ELSE 'S' END POSSUI_TERMO_AG
    , COALESCE(TO_VARCHAR(TO_DATE(TERMO.DT_VALIDADE)),'') AS VALIDADE_DO_TERMO_AG
    , TARG.DESCRICAO AS CLASSIFICACAO
    , REPLACE(REPLACE(REPLACE(A.OBSREP, '|', '/'), CHAR(13), ' '), CHAR(10), ' ') AS OBSERVACAO
    , A.FLG_ELEGIVEL AS ELEGIVEL
    , A.FLG_INTERACAO_GOV AS FLG_INTERACAO_GOV
    , X.DESCRICAO AS LIDER_DE_OPINIAO
    , REPLACE(REPLACE(A.ESTRATEGIA, CHAR(13), ' '), CHAR(10), ' ') AS ESTRATEGIA
    , TO_DATE(A.DT_INSERT) AS DATA_INCLUSAO
    , Z.QTDE_DIAS AS FREQ_NUMERICA
    , A.POTENCIAL AS POTENCIAL
    , REPLACE(REPLACE(BC.UTC, CHAR(13), ' '), CHAR(10), ' ') AS CODIGO_BRICK
    , REPLACE(REPLACE(BC.UTC_NOME, CHAR(13), ' '), CHAR(10), ' ') AS BRICK
    , BC.TIPO AS TIPO_BRICK
    , R.SETOR_CLIENTE AS SETOR_CLIENTE
    , A.COD_TIPO_PROF AS COD_CATEGORIA
    , CAT.DESCRICAO AS CATEGORIA
    , A.FLG_MEDICOVIP AS MEDICO_VIP
    , '' AS DT_ATIVACAO
    , IFNULL(DI.DIAS_SEM_VISITA,'Não Visitado') as DIAS_SEM_VISITA
    , DI.DT_VISITA AS DT_ULTIMA_VISITA
    , A.ORIGEM
    , A.DT_LAKE
FROM DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDMEDREP AS A
INNER JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDNDADOSREP AS R ON A.ORIGEM = R.ORIGEM AND A.MERE_REP = R.EQZ
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDNESTAB AS B ON A.ORIGEM = B.ORIGEM AND A.ESTAB_ID = B.ESTAB_ID
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GDNESTABLOCAL AS C ON B.ORIGEM = C.ORIGEM AND C.ESTAB_ID = B.ESTAB_ID AND B.VIS_LOCAL_ID = C.LOCAL_ID
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_UTC_BRICK AS BC ON C.ORIGEM = BC.ORIGEM AND C.ESTAB_ID = BC.ESTAB_ID
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.Dim_TipoLocalTrabalho AS D ON A.ORIGEM = D.ORIGEM AND B.COD_TIPO_LOCAL = D.COD_TIPO_LOCAL
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.Dim_EspecialidadeProf AS EA ON A.ORIGEM = EA.ORIGEM AND A.COD_ESPEC = EA.COD_ESPEC_PROF
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.Dim_EspecialidadeProf AS EB ON A.ORIGEM = EB.ORIGEM AND A.COD_ESPEC2 = EB.COD_ESPEC_PROF
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.Dim_TipoProf AS CAT ON A.ORIGEM = CAT.ORIGEM AND R.CIA = CAT.CIA AND A.COD_TIPO_PROF = CAT.COD_TIPO_PROF
LEFT JOIN TERMO AS TERMO ON TERMO.ORIGEM = A.ORIGEM AND TERMO.CRM = A.CRM AND TERMO.UF_CRM = A.UF_CRM AND A.COD_TIPO_PROF = TERMO.LETRA
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.Dim_CategoriaProf AS TARG ON A.ORIGEM = TARG.ORIGEM AND A.COD_CATEG_PROF = TARG.COD_CATEG_PROF
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.DIM_GD_N_LIDER_OPINIAO AS X ON A.ORIGEM = X.ORIGEM AND A.COD_LIDER = X.COD_LIDER
LEFT JOIN DB_CRM_SALES_FARMA_DEV.CURATED.Dim_FrequenciaProf AS Z ON A.ORIGEM = Z.ORIGEM AND A.COD_FREQ_PROF = Z.COD_FREQ_PROF
INNER JOIN DB_CRM_SALES_FARMA_DEV.curated.dim_gd_equipes AS equipe ON R.ORIGEM = EQUIPE.ORIGEM AND R.CIA = EQUIPE.EQUI_CIA AND R.EQUIPE = EQUIPE.EQUI_EQUIPE AND equipe.flg_ativo = TRUE
LEFT JOIN DI AS DI ON A.ORIGEM = DI.ORIGEM AND DI.PROF_ID = A.PROF_ID
WHERE A.FLG_ATIVO = TRUE;



create or replace view DB_CRM_ANALYTICS.CURATED.VW_ENDERECOS_A_HARMONIZAR(
	ID_MEDICO_ENDERECO,
	ENDERECO_ORIGINAL
) as
SELECT
    DISTINCT
    H.ID_MEDICO_ENDERECO,
    TRIM(CONCAT_WS(
        ' ',
        TRIM(COALESCE(H.PREFIXO_ENDERECO, '')),
        TRIM(COALESCE(H.ENDERECO, '')),
        TRIM(COALESCE(H.NUMERO_EXTERNO, '')),
        TRIM(COALESCE(H.NUMERO_INTERNO, '')),
        TRIM($$, $$),
        TRIM(COALESCE(H.BAIRRO, '')),
        TRIM($$, $$),
        TRIM(COALESCE(H.CIDADE, '')),
        TRIM($$ - $$),
        TRIM(COALESCE(H.ESTADO, '')),
        TRIM($$, $$),
        TRIM(COALESCE(H.CODIGO_POSTAL, ''))
    )) AS ENDERECO_ORIGINAL
FROM DIM_MEDICO_ENDERECO H
WHERE NOT EXISTS (SELECT 1 FROM ENDERECOS_HARMONIZADOS X WHERE H.ID_MEDICO_ENDERECO = X.ID_MEDICO_ENDERECO)
    AND EXISTS (SELECT 1 FROM FATO_PAINEL P WHERE H.ID_MEDICO = P.ID_MEDICO AND P.ID_PAIS = 1 );


    
CREATE OR REPLACE TABLE FATO_PAINEL_STREAMLIT
AS
SELECT 
    A.ID_MEDICO, B.UF_CRM, B.CRM
    , A.ID_ESPECIALIDADE
    , C.ESPECIALIDADE_DESCRICAO ESPECIALIDADE
    , G.NOME
    , D.SETOR
    , COALESCE(D.SETOR_CLIENTE, '') AS SETOR_CLIENTE
    , COALESCE(D.NOME_SETOR, '') AS NOME_SETOR
    , D.SETOR_HISTORICO
    , D.SETOR_VAGO
    , E.ID_PAIS, E.PAIS
    , F.ID_LABORATORIO, F.LABORATORIO
    , A.STATUS
    , A.VISITADO_1_MESES
    , A.VISITADO_3_MESES
    , A.VISITADO_6_MESES
    , A.VISITADO_12_MESES
    , A.VISITADO
    , A.COD_ESPEC_PROF CODIGO_ESPECIALIDADE_LABORATORIO
    , A.ESPEC_PROF ESPECIALIDADE_LABORATORIO
    , REPLACE(REPLACE(REPLACE(COALESCE(H.ENDERECO_COMPLETO, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') AS ENDERECO_COMPLETO
	, REPLACE(REPLACE(REPLACE(COALESCE(H.PREFIXO_ENDERECO, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') TP_LOGRADOURO
	, REPLACE(REPLACE(REPLACE(COALESCE(HH.LOGRADOURO, H.ENDERECO, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') LOGRADOURO
	, REPLACE(REPLACE(REPLACE(COALESCE(HH.BAIRRO, H.BAIRRO, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') BAIRRO
	, REPLACE(REPLACE(REPLACE(COALESCE(HH.CIDADE, H.CIDADE, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') CIDADE
	, REPLACE(REPLACE(REPLACE(COALESCE(HH.ESTADO, H.ESTADO, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') ESTADO
	, REPLACE(REPLACE(REPLACE(COALESCE(HH.NUMERO, H.NUMERO_EXTERNO, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') NUMERO
	, REPLACE(REPLACE(REPLACE(COALESCE(HH.COMPLEMENTO, H.NUMERO_INTERNO, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') COMPLEMENTO
	, REPLACE(REPLACE(REPLACE(COALESCE(HH.CEP, H.CODIGO_POSTAL, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') CAIXA_POSTAL
    , REPLACE(REPLACE(REPLACE(COALESCE(A.TELEFONE, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') TELEFONE
    , REPLACE(REPLACE(REPLACE(COALESCE(A.EMAIL, ''), $$'$$, ''), CHAR(10), ''), CHAR(13), '') EMAIL
    , CASE WHEN HH.ID_MEDICO_ENDERECO IS NOT NULL THEN 'SIM' ELSE 'NAO' END HARMONIZADO
FROM FATO_PAINEL A
INNER JOIN DIM_MEDICO B ON A.ID_MEDICO = B.ID_MEDICO
LEFT JOIN DIM_ESPECIALIDADE C ON A.ID_ESPECIALIDADE = C.ID_ESPECIALIDADE
LEFT JOIN DIM_FORCAVENDAS D ON A.ID_FORCAVENDAS = D.ID_FORCAVENDAS
INNER JOIN DIM_PAIS E ON A.ID_PAIS = E.ID_PAIS
INNER JOIN DIM_LABORATORIO F ON A.ID_LABORATORIO = F.ID_LABORATORIO
LEFT JOIN DIM_MEDICO_NOME G ON A.ID_MEDICO_NOME = G.ID_MEDICO_NOME
LEFT JOIN DIM_MEDICO_ENDERECO H ON A.ID_MEDICO_ENDERECO = H.ID_MEDICO_ENDERECO
LEFT JOIN ENDERECOS_HARMONIZADOS HH ON A.ID_MEDICO_ENDERECO = HH.ID_MEDICO_ENDERECO
